swagger: '2.0'
info:
  description: ''
  version: 1.0.0
  title: Delilah Restó
  contact:
    email: diegog.guevarab@gmail.com
host: delilah-resto.herokuapp.com
tags:
  - name: Productos
    description: Acceso a los productos de Delilah Restó
  - name: Pedidos
    description: Acceso a los pedidos de Delilah Restó
  - name: Usuarios
    description: Operations about user
schemes:
  - https
paths:
  /products:
    get:
      tags:
        - Productos
      summary: Ver todos los productos
      description: ''
      operationId: getProducts
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '404':
          description: Producto no encontrado
      security:
        - token: []
    post:
      tags:
        - Productos
      summary: Agregar un producto
      description: ''
      operationId: addProduct
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Producto por agregar a la BD
          required: true
          schema:
            $ref: '#/definitions/Product'
      responses:
        '200':
          description: Lista de productos
        '400':
          description: Error en la petición
      security:
        - token: []
  '/products/{productId}':
    get:
      tags:
        - Productos
      summary: Retorna el producto especificado
      description: ''
      operationId: getPetById
      produces:
        - application/json
      parameters:
        - name: productId
          in: path
          description: ID del producto
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Producto correspondiente al ID especificado
          schema:
            $ref: '#/definitions/Product'
        '404':
          description: Producto no encontrado
      security:
        - token: []
    put:
      tags:
        - Productos
      summary: Actualizar un producto
      description: ''
      operationId: updateProduct
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: productId
          in: path
          description: ID del producto a actualizar
          required: true
          type: integer
          format: int64
        - in: body
          name: body
          description: Producto a actualizar
          required: true
          schema:
            $ref: '#/definitions/Product'
      responses:
        '400':
          description: Datos incorrectos
      security:
        - token: []
    delete:
      tags:
        - Productos
      summary: Eliminar un producto
      description: ''
      operationId: deleteProduct
      produces:
        - application/json
      parameters:
        - name: productId
          in: path
          description: Id de producto a eliminar
          required: true
          type: integer
          format: int64
      responses:
        '204':
          description: Eliminación correcta
        '404':
          description: Producto no encontrado
      security:
        - token: []
  /register:
    post:
      tags:
        - 'Usuarios'
      summary: Crear un usuario
      description: Creación de un usuario para usar la app
      operationId: createUser
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Usuario creado
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '201':
          description: Registro exitoso
  /login:
    post:
      tags:
        - 'Usuarios'
      summary: Ingreso de un usuario al sistema
      description: ''
      operationId: loginUser
      produces:
        - application/json
      parameters:
        - name: username
          in: query
          description: El correo o el username del usuario
          required: true
          type: string
        - name: password
          in: query
          description: La contraseña del usuario
          required: true
          type: string
      responses:
        '200':
          description: Login exitoso
          schema:
            type: string
        '400':
          description: Correo/Usuario o contraseña incorrectos
securityDefinitions:
  token:
    type: apiKey
    name: token
    in: header
definitions:
  User:
    type: object
    required:
      - user_name
      - full_name
      - email
      - password
      - phone
      - address
    properties:
      id:
        type: integer
        format: int64
      user_name:
        type: string
      full_name:
        type: string
      email:
        type: string
      password:
        type: string
      phone:
        type: string
      address:
        type: string
  Product:
    type: object
    required:
      - name
      - description
      - price
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
        example: Burrito mexicano
      description:
        type: string
        example: Un burrito repleto de sabor mexicano
      price:
        type: integer
        example: 15000
  Order:
    type: object
    required:
      - payment
      - products
    properties:
      id:
        type: integer
      description:
        type: string
      payment:
        type: string
        enum:
          - Efectivo
          - Débito
          - Crédito
      user_id:
        type: integer
      state:
        type: string
        enum:
          - Nuevo
          - Confirmado
          - Preparando
          - Enviando
          - Entregado
      products:
        type: array
        items:
          $ref: '#/definitions/Product'
      user:
        $ref: '#/definitions/User'